gouda/gouda/listings/urls.py
from django.conf.urls import url
from gouda.listings.views import ListingSearchFormView
from gouda.listings.views import ListingSearchResultsView
from gouda.listings.views import ListingDetailView
from gouda.listings.views import CartUpdateView
from gouda.listings.views import ShippingAddressCreateView
from gouda.listings.views import BraintreeCustomerCreateView
from gouda.listings.views import ReviewOrderView

urlpatterns = [
    url(r'^search/$', ListingSearchFormView.as_view(), name='search'),
    url(r'^search/results/$', ListingSearchResultsView.as_view(), name='search_results'),
    url(r'^(?P<pk>\d+)/$', ListingDetailView.as_view(), name='detail'),
    url(r'^cart/$', CartUpdateView.as_view(), name='cart_update'),
    url(r'^checkout/shipping-address/$', ShippingAddressCreateView.as_view(), name='shipping_address_create'),
    url(r'^checkout/payment/$', BraintreeCustomerCreateView.as_view(), name='customer_create'),
    url(r'^checkout/review/$', ReviewOrderView.as_view(), name='review_order'),
]

gouda/gouda/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from django.contrib.auth.views import password_reset_complete
from django.contrib.auth.views import password_reset_done
from django.core.urlresolvers import reverse_lazy
from django.views.decorators.cache import cache_page, never_cache

from gouda.profiles.forms import LoginForm
from gouda.profiles.forms import PasswordResetForm
from gouda.profiles.forms import SetPasswordForm
from gouda.profiles.views import AccountEditView
from gouda.profiles.views import BookingAlbumDownloadView
from gouda.profiles.views import BookingCsvDownloadView
from gouda.profiles.views import BookingDetailView
from gouda.profiles.views import BookingListView
from gouda.profiles.views import BookingRequestDetailView
from gouda.profiles.views import BookingRequestListView
from gouda.profiles.views import BraintreeMerchantAccountUpdateView
from gouda.profiles.views import CustomerUpdateView
from gouda.profiles.views import ImageUpdateView
from gouda.profiles.views import InboxView
from gouda.profiles.views import PayoutListView
from gouda.profiles.views import ProfileCreateView
from gouda.profiles.views import ProfileUpdateView
from gouda.profiles.views import ShootDetailView
from gouda.profiles.views import ShootListView
from gouda.profiles.views import ThreadView
from gouda.profiles.views import VerifyEmailAddressView
from gouda.profiles.views import password_reset_confirm
from gouda.users.views import login
from gouda.users.views import password_reset

urls = list()
urls.append(url(
    r'^signup/$',
    never_cache(ProfileCreateView.as_view()),
    name='create')
)
urls.append(url(
    r'^password-reset/$',
    password_reset,
    {
        'password_reset_form': PasswordResetForm,
        'template_name': 'profiles/password_reset_form.html',
        'email_template_name': 'profiles/emails/password_reset_body.txt',
        'subject_template_name': 'profiles/emails/password_reset_subject.txt',
        'post_reset_redirect': reverse_lazy('profiles:password_reset_done')
    },
    name='password_reset'
))
urls.append(url(
    r'^password-reset/done/$',
    password_reset_done,
    {
        'template_name': 'profiles/password_reset_done.html'
    },
    name='password_reset_done'
))
urls.append(url(
    r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    VerifyEmailAddressView.as_view(),
    name='verify_email_address'
))

urls.append(url(
    r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    password_reset_confirm,
    {
        'set_password_form': SetPasswordForm,
        'template_name': 'profiles/password_reset_confirm.html',
        'post_reset_redirect': reverse_lazy('index')
    },
    name='password_reset_confirm'
))
urls.append(url(
    r'^reset/done/$',
    password_reset_complete,
    {
        'template_name': 'profiles/password_reset_complete.html'
    },
    name='password_reset_complete'
))
urls.append(url(
    r'^login/$',
    login,
    {
        'template_name': 'profiles/login.html',
        'authentication_form': LoginForm
    },
    name='login'
))
urls.append(url(
    r'^logout/$',
    logout,
    {'next_page': reverse_lazy('index')},
    name='logout'
))
urls.append(url(
    r'^(?P<pk>[0-9]+)/upload/$',
    never_cache(ImageUpdateView.as_view()),
    name='image_update'
))
urls.append(url(
    r'^inbox/$',
    never_cache(InboxView.as_view()),
    name='inbox'
))
urls.append(url(
    r'^inbox/(?P<pk>[0-9]+)/$',
    never_cache(ThreadView.as_view()),
    name='thread'
))
urls.append(url(
    r'^manage-account/payout/$',
    never_cache(BraintreeMerchantAccountUpdateView.as_view()),
    name='braintree_merchant_account_update'
))
urls.append(url(
    r'^manage-account/payout/$',
    never_cache(BraintreeMerchantAccountUpdateView.as_view()),
    name='account_update'
))
urls.append(url(
    r'^edit/$',
    never_cache(ProfileUpdateView.as_view()),
    name='update_profile'
))
urls.append(url(
    r'^account/$',
    never_cache(AccountEditView.as_view()),
    name='edit_account'
))
urls.append(url(
    r'^bookings/$',
    never_cache(BookingListView.as_view()),
    name='booking_list'
))
urls.append(url(
    r'^bookings/(?P<pk>[0-9]+)$',
    never_cache(BookingDetailView.as_view()),
    name='booking_detail'
))
urls.append(url(
    r'^bookings/download/(?P<pk>[0-9]+)$',
    never_cache(BookingAlbumDownloadView.as_view()),
    name='booking_album_download'
))
urls.append(url(
    r'^bookings/csv/$',
    never_cache(BookingCsvDownloadView.as_view()),
    name='booking_csv_download'
))
urls.append(url(
    r'^payouts/$',
    never_cache(PayoutListView.as_view()),
    name='payout_list'
))
urls.append(url(
    r'^shoots/$',
    never_cache(ShootListView.as_view()),
    name='shoot_list'
))
urls.append(url(
    r'^shoots/(?P<pk>[0-9]+)$',
    never_cache(ShootDetailView.as_view()),
    name='shoot_detail'
))
urls.append(url(
    r'^requests/(?P<pk>[0-9]+)$',
    never_cache(BookingRequestDetailView.as_view()),
    name='booking_request_detail'
))
urls.append(url(
    r'^requests/$',
    never_cache(BookingRequestListView.as_view()),
    name='booking_request_list'
))
urls.append(url(
    r'^payment/$',
    never_cache(CustomerUpdateView.as_view()),
    name='customer_update'
))

urlpatterns = urls

gouda/gouda/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.decorators.cache import cache_page
from gouda.routers import Router
from gouda.favorites.api import FavoriteViewSet
from gouda.customers.api import CouponVerificationAPIView
from gouda.customers.api import BraintreeClientTokenView
from gouda.customers.api import BraintreeWebhookNotificationViewSet
from gouda.customers.api import StripeCouponVerificationView
from gouda.customers.api import StripeCustomerViewSet
from gouda.customers.api import StripeEventViewSet
from gouda.profiles.views import ProfileCreateView
from gouda.photographers.views import CreateFoodBookingFormView
from gouda.photographers.views import PhotographerSearchFormView
from gouda.photographers.views import BookingDetailsFormView
from gouda.photographers.api import FoodBookingViewSet
from gouda.photographers.api import BookingImageViewSet
from gouda.photographers.api import BookingAlbumViewSet
from gouda.listings.api import ListingViewSet
from gouda.listings.api import ReviewViewSet
from gouda.views import PrivacyPolicyView
from gouda.views import TermsOfServiceView
from gouda.views import AboutUsView
from gouda.postmaster.api import MessageViewSet
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.sitemaps.views import sitemap
from gouda.sitemaps import StaticViewSitemap
from django.views import static
import django


class UnderConstructionView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('Under Construction')
# Routing
never_cache_router = Router(do_never_cache=True, is_login_required=True)
never_cache_router.register(r'message', MessageViewSet, base_name='message')
never_cache_router.register(r'favorite', FavoriteViewSet, base_name='favorite')
never_cache_router.register(r'stripe_customer', StripeCustomerViewSet, base_name='stripe_customer')
never_cache_router.register(r'stripe_event', StripeEventViewSet, base_name='stripe_event')
cache_router = Router(cache_timeout=3600, is_login_required=True)
router_urls = never_cache_router.urls + cache_router.urls
router_urls.append(
    url(r'^stripe_coupon/(?P<id>\S+)/verify$', StripeCouponVerificationView.as_view(), name='verify_stripe_coupon'),
)


urls = list()

# # Under Construction
# urls.append(
#     url(r'^$', UnderConstructionView.as_view())
# )

# API
urls.append(
    url(r'^api/', include(router_urls, namespace='api')),
)

# Customers API
customer_urls = [
    url(r'^coupon/(?P<code>\S+)/verify$', CouponVerificationAPIView.as_view(), name='verify_coupon'),
]
urls.append(
    url(r'^api/customers/', include(customer_urls, namespace='api_customers')),
)

# Braintree API
braintree_urls = [
    url(r'^clienttoken/$', BraintreeClientTokenView.as_view(), name='client_token'),
]
braintree_router = Router(do_never_cache=True, is_login_required=False)
braintree_router.register(r'b8nt6q09pt', BraintreeWebhookNotificationViewSet, base_name='webhook_notification')
braintree_urls.extend(braintree_router.urls)
urls.append(
    url(r'^api/braintree/', include(braintree_urls, namespace='api_braintree')),
)

# Postmaster API
postmaster_router = Router(do_never_cache=True, is_login_required=True)
postmaster_router.register(r'messages', MessageViewSet, base_name='message')
urls.append(
    url(r'^api/postmaster/', include(postmaster_router.urls, namespace='api_postmaster'))
)

# Favorites API
favorites_router = Router(do_never_cache=True, is_login_required=True)
favorites_router.register(r'favorite', FavoriteViewSet, base_name='favorite')
urls.append(
    url(r'^api/favorites/', include(favorites_router.urls, namespace='api_favorites'))
)

# Listing API
listing_router = Router(cache_timeout=3600)
listing_router.register(r'listing', ListingViewSet, base_name='listing')
listing_router.register(r'review', ReviewViewSet, base_name='review')
urls.append(
    url(r'^api/listings/', include(listing_router.urls, namespace='api_listings'))
)

# Photographer API
photographers_router = Router(do_never_cache=True, is_login_required=True)
photographers_router.register(r'food_bookings', FoodBookingViewSet, base_name='food_booking')
photographers_router.register(r'booking_images', BookingImageViewSet, base_name='booking_image')
photographers_router.register(r'booking_albums', BookingAlbumViewSet, base_name='booking_album')
urls.append(
    url(r'^api/photographers/', include(photographers_router.urls, namespace='api_photographers'))
)

# Hijack
urls.append(
    url(r'^hijack/', include('hijack.urls'))
)

# Admin
urls.append(
    url(r'^cd72789d/', include(admin.site.urls)),
)
urls.append(
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
)

# Photographers
urls.append(
    url(r'^photographers/', include('gouda.photographers.urls', namespace='photographers')),
)
urls.append(url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/$', BookingDetailsFormView.as_view(), name='checkout'))
urls.append(
    url(r'^postmates/$', CreateFoodBookingFormView.as_view(), name='create_food_booking')
)

# Listings
urls.append(
    url(r'^listings/', include('gouda.listings.urls', namespace='listings'))
)

# Profiles
urls.append(
    url(r'^profiles/', include('gouda.profiles.urls', namespace='profiles'))
)

# Static stuff
if settings.DEBUG:
    urls.append(
        url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT})
    )
    urls.append(
        url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT})
    )

    # urls.append(
    #     url(r'^static/bower_components/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/bower_components/'})
    # )
    # urls.append(
    #     url(r'^static/admin/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/lib/python2.7/site-packages/django/contrib/admin/static/admin/'})
    # )
    # urls.append(
    #     url(r'^static/photographers/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/photographers/static/photographers/'})
    # )
    # urls.append(
    #     url(r'^static/profiles/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/photographers/static/profiles/'})
    # )
    # urls.append(
    #     url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/static/'})
    # )

# # Contacts
# urls.append(
#     url(r'', include('gouda.contacts.urls'))
# )

urls.append(
    url(r'^privacy/$', cache_page(86400)(PrivacyPolicyView.as_view()), name='privacy_policy'),
)

urls.append(
    url(r'^terms/$', cache_page(86400)(TermsOfServiceView.as_view()), name='terms_of_service'),
)

urls.append(
    url(r'^about/$', cache_page(86400)(AboutUsView.as_view()), name='about_us'),
)

urls.append(
    url(r'^$', cache_page(60 * 60 * 24)(PhotographerSearchFormView.as_view()), name='index'),
)


sitemaps = {
    'static': StaticViewSitemap,
}
urls.append(
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
)

# Social
urls.append(url('', include('social.apps.django_app.urls', namespace='social')))

urlpatterns = urls

gouda/gouda/listings/templates/listings/base.html
{% extends "content_base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
{% load cache %}
{% load compress %}
{% block body_attributes %}style="overflow-x: hidden;"{% endblock %}

gouda/gouda/listings/templates/listings/cart_update.html
{% extends "listings/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load cache %}
{% load thumbnail %}
{% load list_utils %}
{% load duration %}
{% block html_attributes %}ng-app="gouda.listings.apps.ListingApp"{% endblock %}
{% block facebook_meta_tags %}
    <meta property="og:title" content="{{ listing.title }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="{{ listing.primary_image.image|thumbnail_url:'1024x0' }}"/>
{% endblock %}
{% block title %}Shopping Cart | {{ site_display_name }}{% endblock %}
{% block nav_classes %}navbar navbar--default{% endblock %}
{% block content %}
    <section class="shopping-cart" id="content">
        <div class="container-fluid">
            <div class="card">
                <h1 class="title">Shopping Cart</h1>
                <div class="text-center divider-container">
                    <span class="glyphicon glyphicon-stop divider"></span>
                    <span class="glyphicon glyphicon-stop divider"></span>
                    <span class="glyphicon glyphicon-stop divider"></span>
                </div>
                {% if cart.items.all.count > 0 %}
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ formset.management_form }}
                        {% for form in formset %}
                            {{ form.id }}
                            {{ form.listing }}
                            {{ form.cart }}
                            {{ form.errors }}
                            {% with cart_item=form.instance %}
                                <div class="row cart-item">
                                    <div class="col-sm-3">
                                        <div class="listing-image" style="background-image: url('{{ cart_item.listing.primary_image.image|thumbnail_url:'480x260' }}');"></div>
                                    </div>
                                    <div class="col-sm-5 listing-info">
                                        <h4 class="title"><a href="{{ cart_item.listing.url }}">{{ cart_item.listing.title }}</a></h4>
                                        <h5>from {{ cart_item.listing.profile.full_name }}</h5>
                                        <h5 class="text-muted">{{ cart_item.listing.condition_label }}</h5>
                                        {#                                        <h5>{{ cart_item.listing.currency_symbol }}{{ cart_item.listing.price }}</h5>#}
                                    </div>
                                    <div class="col-sm-1 listing-price">
                                        <h5>{{ cart_item.listing.currency_symbol }}{{ cart_item.listing.price }}</h5>
                                    </div>
                                    <div class="col-sm-3 listing-quantity">
                                        {{ form.quantity }}
                                        <input type="submit" value="Update">
                                    </div>
                                </div>
                                {% if not forloop.last %}<hr/>{% endif %}
                            {% endwith %}
                        {% endfor %}
                    </form>
                    <hr/>
                    <div class="row total-price-container">
                        <div class="col-xs-6 col-sm-9">
                            <p class="subtotal">Subtotal</p>
                        </div>
                        <div class="col-xs-6 col-sm-3">
                            <p class="price">{{ cart.currency_symbol }}{{ cart.subtotal_price }}</p>
                        </div>
                    </div>
                    {#                    <hr/>#}
                    <div class="row checkout-button-container">
                        <div class="col-xs-12 col-sm-offset-7 col-sm-5 col-md-offset-8 col-md-4">
                            <a href="{% url 'listings:shipping_address_create' %}"><kendo-button type="submit" ng-cloak class="k-primary">Proceed to checkout</kendo-button></a>
                        </div>
                    </div>
                {% else %}
                    <h4 class="text-center cart-empty">Your cart is empty.</h4>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

gouda/gouda/listings/templates/listings/search.html
{% extends "listings/base.html" %}
{% load i18n %}
{% load cache %}
{% load staticfiles %}
{% load thumbnail %}
{% load list_utils %}
{% block html_attributes %}ng-app="gouda.listings.apps.ListingApp"{% endblock %}
{% block nav_classes %}navbar navbar-fixed-top navbar--search{% endblock %}
{% block content %}
    {% cache 3600 search %}
        <div class="content" data-spy="scroll" data-target="#navbar-collapse-target" id="listing-search">
            <section id="banner" class="banner">
                <div class="container-fluid banner__container">
                    <video class="banner__container__video" autoplay="autoplay" loop="loop" poster="{% static "listings/images/drones.jpg" %}">
                        <source src="{% static "listings/videos/drones.mp4" %}" type="video/mp4">
                        <source src="{% static "listings/videos/drones.ogg" %}" type="video/ogg">
                        <source src="{% static "listings/videos/drones.webm" %}" type="video/webm">

                    </video>
                    <div class="container form-container">
                        <h1 class="banner__container__title">Recusandae <span class="highlight">hic</span> dolorum.</h1>
                        <form method="get" ng-submit="onSubmit()" jw-action="{% url 'listings:search_results' %}" ng-controller="ListingSearchQueryFormController" novalidate name="form" id="search-query-form">
                            <div class="row input-gang">
                                <div class="col-xs-12 col-sm-10 input-container">
                                    {{ form.query }}
                                </div>
                                <div class="col-xs-12 col-sm-2 input-container">
                                    <kendo-button k-ng-disabled="!isFormValid()" type="submit" ng-cloak class="k-primary">Search</kendo-button>
                                </div>
                            </div>
                        </form>
                        <div class="row about-button-container">
                            <div class="col-xs-12">
                                <kendo-button type="submit" ng-cloak type="button" class="k-primary about-button"><a href="{% url 'about_us' %}">What is {{ site_display_name }}?</a></kendo-button>
                            </div>
                        </div>
{#                        <div class="text-center center-block glyphicon glyphicon-menu-down banner__container__down-arrow"></div>#}
                    </div>
                </div>
            </section>
            <section style="overflow-x: hidden" class="container listing-container">
                <h1 class="text-center title">
                    Aperiam laudantium nisi quasi nam
                </h1>
                <div class="text-center divider-container">
                    <span class="glyphicon glyphicon-stop divider"></span>
                    <span class="glyphicon glyphicon-stop divider"></span>
                    <span class="glyphicon glyphicon-stop divider"></span>
                </div>
                <div class="row listing-row">
                    {% for listing in latest_listings %}
                        <div class="col-sm-4 listing-col">
                            <a href="{{ listing.url }}">
{#                            <a href="{% url 'listings:detail' listing.id %}">#}
                                <div class="listing" style="background-image: url('{{ listing.primary_image.image|thumbnail_url:'480x260' }}');">
                                    <div class="dimmer"></div>
                                    <div class="info">
                                        <p class="title">{{ listing.title }}</p>
                                        <p class="subtitle">{{ listing.currency_symbol }}{{ listing.price|floatformat:0 }}<span class="fa fa-circle"></span>{{ listing.condition_label }}</p>
                                    </div>
{#                                    <div class="info">#}
{#                                        <img class="center-block img-responsive profile-image" src="{% if listing.profile.image %}{{ listing.profile.image|thumbnail_url:'80x80' }}{% else %}{% static "profiles/images/anonymous_profile.png" %}{% endif %}" />#}
{#                                        <p class="text-center title">{{ listing.title }}</p>#}
{#                                    </div>#}
{#                                    <p class="price">#}
{#                                        <sup class="superscript">{{ listing.currency_symbol }}</sup>{{ listing.price|floatformat:0 }}#}
{#                                    </p>#}
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </section>
            <section id="blurbs" class="blurbs">
                <div class="overflow-hidden blurb-1">
                    <div class="container-fluid blurbs__container blurbs__container--beach-1">
                        <h1 class="container text-center blurbs__container__title">
                            {% lorem 10 w random %}.
                        </h1>
                    </div>
                </div>
                <div class="overflow-hidden blurb-2">
                    <div class="container-fluid blurbs__container blurbs__container--beach-2">
                        <h1 class="container text-center blurbs__container__title">
                            {% lorem 15 w random %}
                        </h1>
                    </div>
                </div>
                <div class="overflow-hidden blurb-3">
                    <div class="container-fluid blurbs__container blurbs__container--beach-3">
                        <h1 class="container text-center blurbs__container__title">
                            {% lorem 12 w random %}
                        </h1>
                    </div>
                </div>
            </section>
            <section id="join-the-crew" class="join-the-crew container">
                <div>
                    <div>
                        <h4 class="join-the-crew__title">{{ site_display_name }} is a {% lorem 15 w random %}.</h4>
                        <h5 class="join-the-crew__subtitle">{% lorem 20 w random %}</h5>
                    </div>
                    <div>
                        <a href="{% url 'profiles:create' %}"><kendo-button type="submit" ng-cloak class="k-primary">Join now</kendo-button></a>
                    </div>
                </div>
            </section>
        </div>
    {% endcache %}
{% endblock %}

{% block scripts %}
{% endblock %}

gouda/gouda/listings/templates/listings/search_results.html
{% extends "listings/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load cache %}
{% block html_attributes %}ng-app="gouda.listings.apps.ListingSearchResultsApp"{% endblock %}
{% block title %}Buy Drones | {{ site_display_name }}{% endblock %}
{% block nav_classes %}navbar navbar-fixed-top navbar--default navbar--search-results{% endblock %}
{% block content %}
    {% cache 3600 search_results %}
        <div id="search-results-content" class="content" data-spy="scroll" data-target="#navbar-collapse-target">
            <div class="">f</div>
            <div class="search-container">
                <section id="search-controls" class="container-fluid">
                    <form ng-controller="ListingSearchResultsFormController" novalidate name="form" id="search-form">
                        <div class="row input-gang">
                            <div class="col-xs-12 col-sm-9 col-md-offset-2 col-md-5 input-container">
                                <span class="fa fa-search prefix"></span>
                                {{ form.query }}
                            </div>
                            <div class="col-xs-12 col-sm-3 col-md-3 input-container">
                                {{ form.condition }}
                            </div>
                        </div>
                        <div class="center-block price-range-container">
                            <h4 class="title">Price</h4>
                            <div ng-cloak k-ng-disabled="!areControlsEnabled()" kendo-range-slider="priceRangeSlider" k-on-slide="onPriceRangeSliderSlide(kendoEvent)" class="price-slider" ng-model="price" k-options="priceRangeSliderOptions">
                                <input/>
                                <input/>
                            </div>
                            {% verbatim %}
                            <p ng-cloak class="price pull-left">{{getMinPrice() | currency:'$':0}}</p>
                            <p ng-cloak class="price pull-right">{{getMaxPrice() | currency:'$':0}}<span ng-show="getMaxPrice() >= 1000">+</span></p>
                            {% endverbatim %}
                        </div>
                    </form>
                </section>
                <section id="search-results" class="container-fluid">
                    <div ui-view>
                    </div>
                </section>
            </div>
        </div>
    {% endcache %}
{% endblock %}
{% block footer_class %}{{ block.super }} search-results-footer{% endblock %}