gouda/gouda/photographers/urls.py
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from django.conf.urls import url
from gouda.photographers.views import ScheduleBookingFormView
from gouda.photographers.views import PhotographerApprovalFormView
from gouda.photographers.views import StaffApprovalFormView
from gouda.photographers.views import ClientApprovalFormView
from gouda.photographers.views import ClientRejectionFormView
from gouda.photographers.views import BookingRequestDetailView
from gouda.photographers.views import PhotographerSearchFormView
from gouda.photographers.views import PhotographerSearchResultsView
from gouda.photographers.views import FoodBookingDetailsFormView
from gouda.photographers.views import FoodBookingAddressCreateView
from gouda.photographers.views import BookingDetailsFormView
from gouda.photographers.views import BookingCreateView
from gouda.photographers.views import FoodBookingCreateView
from gouda.photographers.views import BulkBookingCreateView
from gouda.photographers.views import PhotographerRequestCreateView
from gouda.photographers.views import BookingAddressCreateView
from gouda.photographers.views import CustomerCreateView
from gouda.photographers.views import PhotographerCreateView
from gouda.photographers.views import ReviewCreateView
from gouda.photographers.views import BulkBookingFileFormView
from gouda.photographers.views import AcceptBookingRequestView
from gouda.photographers.views import RejectBookingRequestView
from gouda.photographers.views import PhotographerVerificationFormView
from gouda.photographers.views import PhotographerCompletionView
from django.views.decorators.cache import cache_page, never_cache

urlpatterns = [
    url(r'^search/$', PhotographerSearchFormView.as_view(), name='search'),
    url(r'^search/results/$', PhotographerSearchResultsView.as_view(), name='search_results'),
    url(r'^review/(?P<key>[0-9A-Z]{4})/$', ReviewCreateView.as_view(), name='create_review'),

    url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/details/$', BookingDetailsFormView.as_view(), name='get_booking_details'),
    url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/review/$', BookingCreateView.as_view(), name='create_booking'),
    url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/location/$', BookingAddressCreateView.as_view(), name='create_booking_address'),
    # url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/$', BookingDetailsFormView.as_view(), name='checkout'),
    url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/payment/$', CustomerCreateView.as_view(), name='create_customer'),

    url(r'^checkout/food/details/$', FoodBookingDetailsFormView.as_view(), name='get_food_booking_details'),
    url(r'^checkout/food/location/$', FoodBookingAddressCreateView.as_view(), name='create_food_booking_address'),
    url(r'^checkout/food/payment/$', CustomerCreateView.as_view(), name='create_food_customer'),
    url(r'^checkout/food/review/$', FoodBookingCreateView.as_view(), name='create_food_booking'),
    # url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/payment/$', CustomerCreateView.as_view(), name='create_customer'),
    # url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/review/$', BookingCreateView.as_view(), name='create_booking'),
    # url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/$', BookingDetailsFormView.as_view(), name='checkout'),

    url(r'^checkout/bulk/file/$', BulkBookingFileFormView.as_view(), name='get_bulk_booking_file'),
    url(r'^checkout/bulk/payment/$', CustomerCreateView.as_view(), name='create_bulk_customer'),
    url(r'^checkout/bulk/review/$', BulkBookingCreateView.as_view(), name='create_bulk_booking'),

    url(r'^bookings/(?P<pk>[0-9]+)/approve/$', never_cache(ClientApprovalFormView.as_view()), name='client_approval'),
    url(r'^bookings/(?P<pk>[0-9]+)/reject/$', never_cache(ClientRejectionFormView.as_view()), name='client_rejection'),
    url(r'^bookings/(?P<pk>[0-9]+)/staff/approve/$', never_cache(StaffApprovalFormView.as_view()), name='staff_approval'),
    url(r'^shoots/(?P<pk>[0-9]+)/approve/$', never_cache(PhotographerApprovalFormView.as_view()), name='photographer_approval'),

    url(r'^bookings/(?P<pk>[0-9]+)/schedule/(?P<token>.*)/$', never_cache(ScheduleBookingFormView.as_view()), name='schedule_booking'),

    url(r'^request/(?P<pk>[0-9]+)/$', never_cache(BookingRequestDetailView.as_view()), name='booking_request_detail'),
    url(r'^request/(?P<pk>[0-9]+)/accept/(?P<token>.*)/$', never_cache(AcceptBookingRequestView.as_view()), name='accept_booking_request'),
    url(r'^request/(?P<pk>[0-9]+)/reject/(?P<token>.*)/$', never_cache(RejectBookingRequestView.as_view()), name='reject_booking_request'),

    url(r'^request/$', PhotographerRequestCreateView.as_view(), name='create_photographer_request'),
    url(r'^join/$', PhotographerCreateView.as_view(), name='create_photographer'),

    url(r'^verify/$', PhotographerVerificationFormView.as_view(), name='braintree_merchant_account_verification'),
    url(r'^complete/(?P<token>[0-9a-zA-Z:\-_]+)/$', PhotographerCompletionView.as_view(), name='photographer_completion')
]

gouda/gouda/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.decorators.cache import cache_page
from gouda.routers import Router
from gouda.favorites.api import FavoriteViewSet
from gouda.customers.api import CouponVerificationAPIView
from gouda.customers.api import BraintreeClientTokenView
from gouda.customers.api import BraintreeWebhookNotificationViewSet
from gouda.customers.api import StripeCouponVerificationView
from gouda.customers.api import StripeCustomerViewSet
from gouda.customers.api import StripeEventViewSet
from gouda.profiles.views import ProfileCreateView
from gouda.photographers.views import CreateFoodBookingFormView
from gouda.photographers.views import PhotographerSearchFormView
from gouda.photographers.views import BookingDetailsFormView
from gouda.photographers.api import FoodBookingViewSet
from gouda.photographers.api import BookingImageViewSet
from gouda.photographers.api import BookingAlbumViewSet
from gouda.listings.api import ListingViewSet
from gouda.listings.api import ReviewViewSet
from gouda.views import PrivacyPolicyView
from gouda.views import TermsOfServiceView
from gouda.views import AboutUsView
from gouda.postmaster.api import MessageViewSet
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.sitemaps.views import sitemap
from gouda.sitemaps import StaticViewSitemap
from django.views import static
import django


class UnderConstructionView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('Under Construction')
# Routing
never_cache_router = Router(do_never_cache=True, is_login_required=True)
never_cache_router.register(r'message', MessageViewSet, base_name='message')
never_cache_router.register(r'favorite', FavoriteViewSet, base_name='favorite')
never_cache_router.register(r'stripe_customer', StripeCustomerViewSet, base_name='stripe_customer')
never_cache_router.register(r'stripe_event', StripeEventViewSet, base_name='stripe_event')
cache_router = Router(cache_timeout=3600, is_login_required=True)
router_urls = never_cache_router.urls + cache_router.urls
router_urls.append(
    url(r'^stripe_coupon/(?P<id>\S+)/verify$', StripeCouponVerificationView.as_view(), name='verify_stripe_coupon'),
)


urls = list()

# # Under Construction
# urls.append(
#     url(r'^$', UnderConstructionView.as_view())
# )

# API
urls.append(
    url(r'^api/', include(router_urls, namespace='api')),
)

# Customers API
customer_urls = [
    url(r'^coupon/(?P<code>\S+)/verify$', CouponVerificationAPIView.as_view(), name='verify_coupon'),
]
urls.append(
    url(r'^api/customers/', include(customer_urls, namespace='api_customers')),
)

# Braintree API
braintree_urls = [
    url(r'^clienttoken/$', BraintreeClientTokenView.as_view(), name='client_token'),
]
braintree_router = Router(do_never_cache=True, is_login_required=False)
braintree_router.register(r'b8nt6q09pt', BraintreeWebhookNotificationViewSet, base_name='webhook_notification')
braintree_urls.extend(braintree_router.urls)
urls.append(
    url(r'^api/braintree/', include(braintree_urls, namespace='api_braintree')),
)

# Postmaster API
postmaster_router = Router(do_never_cache=True, is_login_required=True)
postmaster_router.register(r'messages', MessageViewSet, base_name='message')
urls.append(
    url(r'^api/postmaster/', include(postmaster_router.urls, namespace='api_postmaster'))
)

# Favorites API
favorites_router = Router(do_never_cache=True, is_login_required=True)
favorites_router.register(r'favorite', FavoriteViewSet, base_name='favorite')
urls.append(
    url(r'^api/favorites/', include(favorites_router.urls, namespace='api_favorites'))
)

# Listing API
listing_router = Router(cache_timeout=3600)
listing_router.register(r'listing', ListingViewSet, base_name='listing')
listing_router.register(r'review', ReviewViewSet, base_name='review')
urls.append(
    url(r'^api/listings/', include(listing_router.urls, namespace='api_listings'))
)

# Photographer API
photographers_router = Router(do_never_cache=True, is_login_required=True)
photographers_router.register(r'food_bookings', FoodBookingViewSet, base_name='food_booking')
photographers_router.register(r'booking_images', BookingImageViewSet, base_name='booking_image')
photographers_router.register(r'booking_albums', BookingAlbumViewSet, base_name='booking_album')
urls.append(
    url(r'^api/photographers/', include(photographers_router.urls, namespace='api_photographers'))
)

# Hijack
urls.append(
    url(r'^hijack/', include('hijack.urls'))
)

# Admin
urls.append(
    url(r'^cd72789d/', include(admin.site.urls)),
)
urls.append(
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
)

# Photographers
urls.append(
    url(r'^photographers/', include('gouda.photographers.urls', namespace='photographers')),
)
urls.append(url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/$', BookingDetailsFormView.as_view(), name='checkout'))
urls.append(
    url(r'^postmates/$', CreateFoodBookingFormView.as_view(), name='create_food_booking')
)

# Listings
urls.append(
    url(r'^listings/', include('gouda.listings.urls', namespace='listings'))
)

# Profiles
urls.append(
    url(r'^profiles/', include('gouda.profiles.urls', namespace='profiles'))
)

# Static stuff
if settings.DEBUG:
    urls.append(
        url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT})
    )
    urls.append(
        url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT})
    )

    # urls.append(
    #     url(r'^static/bower_components/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/bower_components/'})
    # )
    # urls.append(
    #     url(r'^static/admin/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/lib/python2.7/site-packages/django/contrib/admin/static/admin/'})
    # )
    # urls.append(
    #     url(r'^static/photographers/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/photographers/static/photographers/'})
    # )
    # urls.append(
    #     url(r'^static/profiles/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/photographers/static/profiles/'})
    # )
    # urls.append(
    #     url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/static/'})
    # )

# # Contacts
# urls.append(
#     url(r'', include('gouda.contacts.urls'))
# )

urls.append(
    url(r'^privacy/$', cache_page(86400)(PrivacyPolicyView.as_view()), name='privacy_policy'),
)

urls.append(
    url(r'^terms/$', cache_page(86400)(TermsOfServiceView.as_view()), name='terms_of_service'),
)

urls.append(
    url(r'^about/$', cache_page(86400)(AboutUsView.as_view()), name='about_us'),
)

urls.append(
    url(r'^$', cache_page(60 * 60 * 24)(PhotographerSearchFormView.as_view()), name='index'),
)


sitemaps = {
    'static': StaticViewSitemap,
}
urls.append(
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
)

# Social
urls.append(url('', include('social.apps.django_app.urls', namespace='social')))

urlpatterns = urls

gouda/gouda/photographers/templates/photographers/snippets/booking_card_snippet.html
{% load tz %}
<div id="reschedule-booking-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span class="fa fa-times"></span></button>
                <h4 class="modal-title">Reschedule your shoot</h4>
            </div>
            <form method="post" action="{{ request.path }}" role="form" name="form" data-parsley-validate="">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <label>When will this job be done?</label>
                            {{ form.date }}
                        </div>
                        <div class="col-sm-6">
                            <label>What time will you start?</label>
                            {{ form.start_time }}
                        </div>
                        <div class="col-sm-6">
                            <label>What time will you finish?</label>
                            {{ form.stop_time }}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-12 col-md-offset-7 col-md-5">
                            <button type="submit" class="k-button k-primary">Reschedule</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="card">
    <div class="header">
        <h2 class="title">{{ booking.get_display_name }}</h2>
    </div>
    <div class="content">
        <div class="row">
            <div class="col-xs-12">
                <h4 class="regular-font">Status</h4>
                {% if booking.did_client_approve %}
                    <p class="text-success regular-font">Approved</p>
                {% elif booking.did_client_reject and not booking.did_staff_approve and not booking.did_photographer_approve %}
                    <p class="text-danger regular-font">Rejected by Client</p>
                {% else %}
                    <p class="text-warning regular-font">Pending Approval</p>
                {% endif %}
            </div>
        </div>
        {% if booking.foodbooking %}
            {% with food_booking=booking.foodbooking %}
                <div class="row">
                    <div class="col-xs-12">
                        <h4 class="regular-font">Job Details</h4>
                        <p>Is this a full menu shoot? <span class="regular-font">{{ food_booking.is_full_menu_shoot|yesno|capfirst }}</span></p>
                        <p>Is this booking confirmed with the restaurant? <span class="regular-font">{{ food_booking.is_confirmed_with_restaurant|yesno|capfirst }}</span></p>
                        {% if booking.time_range %}
                            <p>{{ booking.time_range.lower|timezone:booking.address.time_zone|date }}</p>
                            <p>{{ booking.time_range.lower|timezone:booking.address.time_zone|date:"g:i A e" }} - {{ booking.time_range.upper|timezone:booking.address.time_zone|date:"g:i A e" }}</p>
                        {% endif %}
                        {% if user.is_staff or is_shoot_detail %}<p><a href="#" data-toggle="modal" data-target="#reschedule-booking-modal"><span class="fa fa-calendar"></span> Reschedule this shoot</a></p>{% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <h4 class="regular-font">Location</h4>
                        <p>{{ food_booking.restaurant_name }}</p>
                        <p>{{ booking.address.formatted_street_address }}</p>
                        <p>{{ booking.address.formatted_locality }}, {{ booking.address.formatted_region }} {{ booking.address.formatted_postal_code }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <h4 class="regular-font">Contact details</h4>
                        <p>{{ food_booking.contact_name }}</p>
{#                        <p><span class="fa fa-phone"></span> {{ food_booking.contact_phone_number }}</p>#}
                        <p><span class="fa fa-envelope"></span> {{ food_booking.contact_email_address }}</p>
                    </div>
                </div>
            {% endwith %}
        {% else %}
            <div class="row">
                <div class="col-xs-12">
                    <h4 class="regular-font">Job Details</h4>
                    <p>{{ booking.service_type_label }}</p>
                    {% if booking.time_range %}
                        <p>{{ booking.time_range.lower|date }}</p>
                        <p>{{ booking.time_range.upper|date:"g:i A" }} - {{ booking.time_range.lower|date:"g:i A" }}</p>
                    {% endif %}
                    <p><span class="fa fa-phone"></span> {{ booking.phone_number }}</p>
                    {% if user.is_staff or is_shoot_detail %}<p><a href="#" data-toggle="modal" data-target="#reschedule-booking-modal"><span class="fa fa-calendar"></span> Reschedule this shoot</a></p>{% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <h4 class="regular-font">Location</h4>
                    <p>{{ booking.address.formatted_street_address }}</p>
                    <p>{{ booking.address.formatted_locality }}, {{ booking.address.formatted_region }} {{ booking.address.formatted_postal_code }}</p>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-xs-12">
                <h4 class="regular-font">Photographer</h4>
                {% if booking.photographer %}
                    <p>{{ booking.photographer.display_name }}</p>
                {% else %}
                    <p>Unassigned</p>
                {% endif %}
            </div>
        </div>
        {% if booking.did_photographer_approve %}
            <div class="row">
                <div class="col-xs-12">
                    <h4 class="regular-font">Number of shots</h4>
                    <p>{{ booking.num_shots }}</p>
                </div>
            </div>
        {% endif %}
        {% if booking.foodbooking and booking.foodbooking.menu_url %}
            <div class="row">
                <div class="col-xs-12">
                    <h4 class="regular-font">Menu</h4>
                    <p><a href="{{ booking.foodbooking.menu_url }}">See {{ booking.foodbooking.restaurant_name }}'s Menu</a></p>
                </div>
            </div>
        {% endif %}
        {% if booking.foodbooking %}
            <div class="row">
                <div class="col-xs-12">
                    <h4 class="regular-font">Menu Items</h4>
                    <div id="chips"></div>
                </div>
            </div>
        {% endif %}
        {% if booking.message %}
            <div class="row">
                <div class="col-xs-12">
                    <h4 class="regular-font">Message</h4>
                    <p>{{ booking.message }}</p>
                </div>
            </div>
        {% endif %}
        {% if is_shoot_detail %}
            {% if not booking.did_photographer_approve and booking.images.count > 0 %}
                <hr/>
                <div class="row">
                    <div class="col-xs-12">
                        <a href="{% url 'photographers:photographer_approval' booking.id %}"><button class="k-button k-primary">Finalize this shoot</button></a>
                    </div>
                </div>
            {% endif %}
        {% elif is_booking_detail %}
            {% if user.is_staff %}
                {% if not booking.did_staff_approve and booking.did_photographer_approve %}
                    <hr/>
                    <div class="row">
                        <div class="col-xs-12">
                            <a href="{% url 'photographers:staff_approval' booking.id %}"><button class="k-button k-primary green"><span class="fa fa-thumbs-up"></span> Submit to client</button></a>
                        </div>
                    </div>
                {% endif %}
            {% else %}
                {% if booking.did_staff_approve and not booking.did_client_approve and not booking.did_client_reject %}
                    <hr/>
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="{% url 'photographers:client_rejection' booking.id %}"><button class="k-button k-primary red"><span class="fa fa-thumbs-down"></span> Reject this booking</button></a>
                        </div>
                        <div class="col-xs-6">
                            <a href="{% url 'photographers:client_approval' booking.id %}"><button class="k-button k-primary green"><span class="fa fa-thumbs-up"></span> Approve this booking</button></a>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>
</div>