gouda/gouda/photographers/urls.py
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from django.conf.urls import url
from gouda.photographers.views import ScheduleBookingFormView
from gouda.photographers.views import PhotographerApprovalFormView
from gouda.photographers.views import StaffApprovalFormView
from gouda.photographers.views import ClientApprovalFormView
from gouda.photographers.views import ClientRejectionFormView
from gouda.photographers.views import BookingRequestDetailView
from gouda.photographers.views import PhotographerSearchFormView
from gouda.photographers.views import PhotographerSearchResultsView
from gouda.photographers.views import FoodBookingDetailsFormView
from gouda.photographers.views import FoodBookingAddressCreateView
from gouda.photographers.views import BookingDetailsFormView
from gouda.photographers.views import BookingCreateView
from gouda.photographers.views import FoodBookingCreateView
from gouda.photographers.views import BulkBookingCreateView
from gouda.photographers.views import PhotographerRequestCreateView
from gouda.photographers.views import BookingAddressCreateView
from gouda.photographers.views import CustomerCreateView
from gouda.photographers.views import PhotographerCreateView
from gouda.photographers.views import ReviewCreateView
from gouda.photographers.views import BulkBookingFileFormView
from gouda.photographers.views import AcceptBookingRequestView
from gouda.photographers.views import RejectBookingRequestView
from gouda.photographers.views import PhotographerVerificationFormView
from gouda.photographers.views import PhotographerCompletionView
from django.views.decorators.cache import cache_page, never_cache

urlpatterns = [
    url(r'^search/$', PhotographerSearchFormView.as_view(), name='search'),
    url(r'^search/results/$', PhotographerSearchResultsView.as_view(), name='search_results'),
    url(r'^review/(?P<key>[0-9A-Z]{4})/$', ReviewCreateView.as_view(), name='create_review'),

    url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/details/$', BookingDetailsFormView.as_view(), name='get_booking_details'),
    url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/review/$', BookingCreateView.as_view(), name='create_booking'),
    url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/location/$', BookingAddressCreateView.as_view(), name='create_booking_address'),
    # url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/$', BookingDetailsFormView.as_view(), name='checkout'),
    url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/payment/$', CustomerCreateView.as_view(), name='create_customer'),

    url(r'^checkout/food/details/$', FoodBookingDetailsFormView.as_view(), name='get_food_booking_details'),
    url(r'^checkout/food/location/$', FoodBookingAddressCreateView.as_view(), name='create_food_booking_address'),
    url(r'^checkout/food/payment/$', CustomerCreateView.as_view(), name='create_food_customer'),
    url(r'^checkout/food/review/$', FoodBookingCreateView.as_view(), name='create_food_booking'),
    # url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/payment/$', CustomerCreateView.as_view(), name='create_customer'),
    # url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/review/$', BookingCreateView.as_view(), name='create_booking'),
    # url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/$', BookingDetailsFormView.as_view(), name='checkout'),

    url(r'^checkout/bulk/file/$', BulkBookingFileFormView.as_view(), name='get_bulk_booking_file'),
    url(r'^checkout/bulk/payment/$', CustomerCreateView.as_view(), name='create_bulk_customer'),
    url(r'^checkout/bulk/review/$', BulkBookingCreateView.as_view(), name='create_bulk_booking'),

    url(r'^bookings/(?P<pk>[0-9]+)/approve/$', never_cache(ClientApprovalFormView.as_view()), name='client_approval'),
    url(r'^bookings/(?P<pk>[0-9]+)/reject/$', never_cache(ClientRejectionFormView.as_view()), name='client_rejection'),
    url(r'^bookings/(?P<pk>[0-9]+)/staff/approve/$', never_cache(StaffApprovalFormView.as_view()), name='staff_approval'),
    url(r'^shoots/(?P<pk>[0-9]+)/approve/$', never_cache(PhotographerApprovalFormView.as_view()), name='photographer_approval'),

    url(r'^bookings/(?P<pk>[0-9]+)/schedule/(?P<token>.*)/$', never_cache(ScheduleBookingFormView.as_view()), name='schedule_booking'),

    url(r'^request/(?P<pk>[0-9]+)/$', never_cache(BookingRequestDetailView.as_view()), name='booking_request_detail'),
    url(r'^request/(?P<pk>[0-9]+)/accept/(?P<token>.*)/$', never_cache(AcceptBookingRequestView.as_view()), name='accept_booking_request'),
    url(r'^request/(?P<pk>[0-9]+)/reject/(?P<token>.*)/$', never_cache(RejectBookingRequestView.as_view()), name='reject_booking_request'),

    url(r'^request/$', PhotographerRequestCreateView.as_view(), name='create_photographer_request'),
    url(r'^join/$', PhotographerCreateView.as_view(), name='create_photographer'),

    url(r'^verify/$', PhotographerVerificationFormView.as_view(), name='braintree_merchant_account_verification'),
    url(r'^complete/(?P<token>[0-9a-zA-Z:\-_]+)/$', PhotographerCompletionView.as_view(), name='photographer_completion')
]

gouda/gouda/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from django.contrib.auth.views import password_reset_complete
from django.contrib.auth.views import password_reset_done
from django.core.urlresolvers import reverse_lazy
from django.views.decorators.cache import cache_page, never_cache

from gouda.profiles.forms import LoginForm
from gouda.profiles.forms import PasswordResetForm
from gouda.profiles.forms import SetPasswordForm
from gouda.profiles.views import AccountEditView
from gouda.profiles.views import BookingAlbumDownloadView
from gouda.profiles.views import BookingCsvDownloadView
from gouda.profiles.views import BookingDetailView
from gouda.profiles.views import BookingListView
from gouda.profiles.views import BookingRequestDetailView
from gouda.profiles.views import BookingRequestListView
from gouda.profiles.views import BraintreeMerchantAccountUpdateView
from gouda.profiles.views import CustomerUpdateView
from gouda.profiles.views import ImageUpdateView
from gouda.profiles.views import InboxView
from gouda.profiles.views import PayoutListView
from gouda.profiles.views import ProfileCreateView
from gouda.profiles.views import ProfileUpdateView
from gouda.profiles.views import ShootDetailView
from gouda.profiles.views import ShootListView
from gouda.profiles.views import ThreadView
from gouda.profiles.views import VerifyEmailAddressView
from gouda.profiles.views import password_reset_confirm
from gouda.users.views import login
from gouda.users.views import password_reset

urls = list()
urls.append(url(
    r'^signup/$',
    never_cache(ProfileCreateView.as_view()),
    name='create')
)
urls.append(url(
    r'^password-reset/$',
    password_reset,
    {
        'password_reset_form': PasswordResetForm,
        'template_name': 'profiles/password_reset_form.html',
        'email_template_name': 'profiles/emails/password_reset_body.txt',
        'subject_template_name': 'profiles/emails/password_reset_subject.txt',
        'post_reset_redirect': reverse_lazy('profiles:password_reset_done')
    },
    name='password_reset'
))
urls.append(url(
    r'^password-reset/done/$',
    password_reset_done,
    {
        'template_name': 'profiles/password_reset_done.html'
    },
    name='password_reset_done'
))
urls.append(url(
    r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    VerifyEmailAddressView.as_view(),
    name='verify_email_address'
))

urls.append(url(
    r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    password_reset_confirm,
    {
        'set_password_form': SetPasswordForm,
        'template_name': 'profiles/password_reset_confirm.html',
        'post_reset_redirect': reverse_lazy('index')
    },
    name='password_reset_confirm'
))
urls.append(url(
    r'^reset/done/$',
    password_reset_complete,
    {
        'template_name': 'profiles/password_reset_complete.html'
    },
    name='password_reset_complete'
))
urls.append(url(
    r'^login/$',
    login,
    {
        'template_name': 'profiles/login.html',
        'authentication_form': LoginForm
    },
    name='login'
))
urls.append(url(
    r'^logout/$',
    logout,
    {'next_page': reverse_lazy('index')},
    name='logout'
))
urls.append(url(
    r'^(?P<pk>[0-9]+)/upload/$',
    never_cache(ImageUpdateView.as_view()),
    name='image_update'
))
urls.append(url(
    r'^inbox/$',
    never_cache(InboxView.as_view()),
    name='inbox'
))
urls.append(url(
    r'^inbox/(?P<pk>[0-9]+)/$',
    never_cache(ThreadView.as_view()),
    name='thread'
))
urls.append(url(
    r'^manage-account/payout/$',
    never_cache(BraintreeMerchantAccountUpdateView.as_view()),
    name='braintree_merchant_account_update'
))
urls.append(url(
    r'^manage-account/payout/$',
    never_cache(BraintreeMerchantAccountUpdateView.as_view()),
    name='account_update'
))
urls.append(url(
    r'^edit/$',
    never_cache(ProfileUpdateView.as_view()),
    name='update_profile'
))
urls.append(url(
    r'^account/$',
    never_cache(AccountEditView.as_view()),
    name='edit_account'
))
urls.append(url(
    r'^bookings/$',
    never_cache(BookingListView.as_view()),
    name='booking_list'
))
urls.append(url(
    r'^bookings/(?P<pk>[0-9]+)$',
    never_cache(BookingDetailView.as_view()),
    name='booking_detail'
))
urls.append(url(
    r'^bookings/download/(?P<pk>[0-9]+)$',
    never_cache(BookingAlbumDownloadView.as_view()),
    name='booking_album_download'
))
urls.append(url(
    r'^bookings/csv/$',
    never_cache(BookingCsvDownloadView.as_view()),
    name='booking_csv_download'
))
urls.append(url(
    r'^payouts/$',
    never_cache(PayoutListView.as_view()),
    name='payout_list'
))
urls.append(url(
    r'^shoots/$',
    never_cache(ShootListView.as_view()),
    name='shoot_list'
))
urls.append(url(
    r'^shoots/(?P<pk>[0-9]+)$',
    never_cache(ShootDetailView.as_view()),
    name='shoot_detail'
))
urls.append(url(
    r'^requests/(?P<pk>[0-9]+)$',
    never_cache(BookingRequestDetailView.as_view()),
    name='booking_request_detail'
))
urls.append(url(
    r'^requests/$',
    never_cache(BookingRequestListView.as_view()),
    name='booking_request_list'
))
urls.append(url(
    r'^payment/$',
    never_cache(CustomerUpdateView.as_view()),
    name='customer_update'
))

urlpatterns = urls

gouda/gouda/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.decorators.cache import cache_page
from gouda.routers import Router
from gouda.favorites.api import FavoriteViewSet
from gouda.customers.api import CouponVerificationAPIView
from gouda.customers.api import BraintreeClientTokenView
from gouda.customers.api import BraintreeWebhookNotificationViewSet
from gouda.customers.api import StripeCouponVerificationView
from gouda.customers.api import StripeCustomerViewSet
from gouda.customers.api import StripeEventViewSet
from gouda.profiles.views import ProfileCreateView
from gouda.photographers.views import CreateFoodBookingFormView
from gouda.photographers.views import PhotographerSearchFormView
from gouda.photographers.views import BookingDetailsFormView
from gouda.photographers.api import FoodBookingViewSet
from gouda.photographers.api import BookingImageViewSet
from gouda.photographers.api import BookingAlbumViewSet
from gouda.listings.api import ListingViewSet
from gouda.listings.api import ReviewViewSet
from gouda.views import PrivacyPolicyView
from gouda.views import TermsOfServiceView
from gouda.views import AboutUsView
from gouda.postmaster.api import MessageViewSet
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.sitemaps.views import sitemap
from gouda.sitemaps import StaticViewSitemap
from django.views import static
import django


class UnderConstructionView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('Under Construction')
# Routing
never_cache_router = Router(do_never_cache=True, is_login_required=True)
never_cache_router.register(r'message', MessageViewSet, base_name='message')
never_cache_router.register(r'favorite', FavoriteViewSet, base_name='favorite')
never_cache_router.register(r'stripe_customer', StripeCustomerViewSet, base_name='stripe_customer')
never_cache_router.register(r'stripe_event', StripeEventViewSet, base_name='stripe_event')
cache_router = Router(cache_timeout=3600, is_login_required=True)
router_urls = never_cache_router.urls + cache_router.urls
router_urls.append(
    url(r'^stripe_coupon/(?P<id>\S+)/verify$', StripeCouponVerificationView.as_view(), name='verify_stripe_coupon'),
)


urls = list()

# # Under Construction
# urls.append(
#     url(r'^$', UnderConstructionView.as_view())
# )

# API
urls.append(
    url(r'^api/', include(router_urls, namespace='api')),
)

# Customers API
customer_urls = [
    url(r'^coupon/(?P<code>\S+)/verify$', CouponVerificationAPIView.as_view(), name='verify_coupon'),
]
urls.append(
    url(r'^api/customers/', include(customer_urls, namespace='api_customers')),
)

# Braintree API
braintree_urls = [
    url(r'^clienttoken/$', BraintreeClientTokenView.as_view(), name='client_token'),
]
braintree_router = Router(do_never_cache=True, is_login_required=False)
braintree_router.register(r'b8nt6q09pt', BraintreeWebhookNotificationViewSet, base_name='webhook_notification')
braintree_urls.extend(braintree_router.urls)
urls.append(
    url(r'^api/braintree/', include(braintree_urls, namespace='api_braintree')),
)

# Postmaster API
postmaster_router = Router(do_never_cache=True, is_login_required=True)
postmaster_router.register(r'messages', MessageViewSet, base_name='message')
urls.append(
    url(r'^api/postmaster/', include(postmaster_router.urls, namespace='api_postmaster'))
)

# Favorites API
favorites_router = Router(do_never_cache=True, is_login_required=True)
favorites_router.register(r'favorite', FavoriteViewSet, base_name='favorite')
urls.append(
    url(r'^api/favorites/', include(favorites_router.urls, namespace='api_favorites'))
)

# Listing API
listing_router = Router(cache_timeout=3600)
listing_router.register(r'listing', ListingViewSet, base_name='listing')
listing_router.register(r'review', ReviewViewSet, base_name='review')
urls.append(
    url(r'^api/listings/', include(listing_router.urls, namespace='api_listings'))
)

# Photographer API
photographers_router = Router(do_never_cache=True, is_login_required=True)
photographers_router.register(r'food_bookings', FoodBookingViewSet, base_name='food_booking')
photographers_router.register(r'booking_images', BookingImageViewSet, base_name='booking_image')
photographers_router.register(r'booking_albums', BookingAlbumViewSet, base_name='booking_album')
urls.append(
    url(r'^api/photographers/', include(photographers_router.urls, namespace='api_photographers'))
)

# Hijack
urls.append(
    url(r'^hijack/', include('hijack.urls'))
)

# Admin
urls.append(
    url(r'^cd72789d/', include(admin.site.urls)),
)
urls.append(
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
)

# Photographers
urls.append(
    url(r'^photographers/', include('gouda.photographers.urls', namespace='photographers')),
)
urls.append(url(r'^checkout/(?P<booking_checkout_url>[0-9A-Z]{4})/$', BookingDetailsFormView.as_view(), name='checkout'))
urls.append(
    url(r'^postmates/$', CreateFoodBookingFormView.as_view(), name='create_food_booking')
)

# Listings
urls.append(
    url(r'^listings/', include('gouda.listings.urls', namespace='listings'))
)

# Profiles
urls.append(
    url(r'^profiles/', include('gouda.profiles.urls', namespace='profiles'))
)

# Static stuff
if settings.DEBUG:
    urls.append(
        url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT})
    )
    urls.append(
        url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT})
    )

    # urls.append(
    #     url(r'^static/bower_components/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/bower_components/'})
    # )
    # urls.append(
    #     url(r'^static/admin/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/lib/python2.7/site-packages/django/contrib/admin/static/admin/'})
    # )
    # urls.append(
    #     url(r'^static/photographers/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/photographers/static/photographers/'})
    # )
    # urls.append(
    #     url(r'^static/profiles/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/photographers/static/profiles/'})
    # )
    # urls.append(
    #     url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/opt/gouda/gouda/gouda/static/'})
    # )

# # Contacts
# urls.append(
#     url(r'', include('gouda.contacts.urls'))
# )

urls.append(
    url(r'^privacy/$', cache_page(86400)(PrivacyPolicyView.as_view()), name='privacy_policy'),
)

urls.append(
    url(r'^terms/$', cache_page(86400)(TermsOfServiceView.as_view()), name='terms_of_service'),
)

urls.append(
    url(r'^about/$', cache_page(86400)(AboutUsView.as_view()), name='about_us'),
)

urls.append(
    url(r'^$', cache_page(60 * 60 * 24)(PhotographerSearchFormView.as_view()), name='index'),
)


sitemaps = {
    'static': StaticViewSitemap,
}
urls.append(
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
)

# Social
urls.append(url('', include('social.apps.django_app.urls', namespace='social')))

urlpatterns = urls

gouda/gouda/photographers/templates/photographers/base.html
{% extends "content_base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
{% load cache %}
{% load compress %}
{% block body_attributes %}style="overflow-x: hidden;"{% endblock %}

gouda/gouda/photographers/templates/photographers/search.html
{% extends "photographers/base.html" %}
{% load i18n %}
{% load cache %}
{% load staticfiles %}
{% load thumbnail %}
{% load list_utils %}
{% block html_attributes %}ng-app="gouda.photographers.apps.PhotographerApp"{% endblock %}
{#{% block nav_classes %}navbar navbar-fixed-top navbar--search{% endblock %}#}
{% block nav %}
    <nav class="navbar navbar-fixed-top navbar--search" role="navigation">
        <div class="container-fluid messages">
            {% if messages %}
                <ul class="">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand hvr-fade" href="{% url 'index' %}">{{ site_display_name }}</a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-target">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-target">
                <ul class="nav navbar-nav navbar-right nav-link-container">
                    {% if user.is_authenticated %}
                        <li class="nav-profile-link-container"><a id="nav-profile-link" class="hvr-fade"
                                                                  href="{% url 'profiles:booking_list' %}"><img
                                class="img-circle nav-profile-image" src="
                                {% if user.profile.image %}{{ user.profile.image|thumbnail_url:'35x35' }}{% else %}{% static "profiles/images/anonymous_profile.png" %}{% endif %}" />{{ user.first_name }}
                        </a></li>
                        {#                        <li><a id="nav-profile-link" class="hvr-fade" href="#">{{ user.first_name }}</a></li>#}
                        <li><a class="hvr-fade" href="{% url 'profiles:logout' %}">log out</a></li>
                    {% else %}
                        <li><a class="hvr-fade" href="{% url 'profiles:create' %}">sign up</a></li>
                        <li><a class="hvr-fade" href="{% url 'profiles:login' %}?next={% firstof request.path '/' %}">log
                            in</a></li>
                    {% endif %}
                    <li><a id="nav-list-your-pad" class="hvr-fade" href="{% url 'photographers:create_photographer' %}">Become
                        a photographer</a></li>

                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="content" data-spy="scroll" data-target="#navbar-collapse-target" id="photographer-search">
        <section id="banner" class="banner">
            <div class="container-fluid banner__container">
                <video class="banner__container__video" autoplay="autoplay" loop="loop"
                       poster="{% static "photographers/images/poster.jpg" %}">
                    <source src="{% static "photographers/videos/listings.mp4" %}" type="video/mp4">
                    <source src="{% static "photographers/videos/listings.ogg" %}" type="video/ogg">
                    <source src="{% static "photographers/videos/listings.webm" %}" type="video/webm">

                </video>
                <div class="container form-container">
                    <h1 class="banner__container__title">Bulk product <span class="highlight">photography</span> for
                        online businesses.</h1>
                    {#                        <form method="get" action="{% if user.is_authenticated and user.profile.is_active %}{% url "photographers:checkout" %}{% else %}{% url "photographers:create_photographer_request" %}{% endif %}" ng-controller="PhotographerBookingQueryFormController" novalidate name="form" id="search-query-form">#}
                    <form method="post" action="{{ request.path }}" name="form" id="search-query-form"
                          data-parsley-validate="">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12r">
                                {{ form.region }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12">
                                {{ form.service_type }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6">
                                {{ form.date }}
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                {{ form.time_period }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <button type="submit" class="k-primary k-button">Book a Photographer</button>
                            </div>
                        </div>
                    </form>
                    {#                        <div class="row about-button-container">#}
                    {#                            <div class="col-xs-12">#}
                    {#                                <kendo-button type="submit" ng-cloak type="button" class="k-primary about-button"><a href="{% url 'about_us' %}">What is {{ site_display_name }}?</a></kendo-button>#}
                    {#                            </div>#}
                    {#                        </div>#}
                    {#                        <div class="text-center center-block glyphicon glyphicon-menu-down banner__container__down-arrow"></div>#}
                </div>
            </div>
        </section>
        <section style="overflow-x: hidden" class="container photographer-container">
            <h1 class="text-center">
                How {{ site_display_name }} works
            </h1>
            <div class="text-center divider-container">
                <span class="glyphicon glyphicon-stop divider"></span>
                <span class="glyphicon glyphicon-stop divider"></span>
                <span class="glyphicon glyphicon-stop divider"></span>
            </div>
            <div class="row how-it-works-row">
                <div class="col-sm-4 text-center">
                    <div class="col-image-container">
                        <div class="feature-one"></div>
                    </div>
                    <h2 class="col-title">Tell us what you need</h2>
                    <h4 class="col-subtitle">Fill out the form at the top of the page and we will handle finding the
                        best photographer for your needs.</h4>
                </div>
                <div class="col-sm-4 text-center">
                    <div class="col-image-container">
                        <div class="feature-two"></div>
                    </div>
                    <h2 class="col-title">Enjoy the shoot</h2>
                    <h4 class="col-subtitle">Whether it is a property for sale or improving your brand, our expert
                        photographers will take care in getting you the best results.</h4>
                </div>
                <div class="col-sm-4 text-center">
                    <div class="col-image-container">
                        <div class="feature-three"></div>
                    </div>
                    <h2 class="col-title">Rest easy</h2>
                    <h4 class="col-subtitle">Your job is not complete until you are 100% satisfied. That's a
                        guarantee.</h4>
                </div>
            </div>
        </section>
        <section id="blurbs" class="blurbs">
            <div class="overflow-hidden blurb-1">
                <div class="container-fluid blurbs__container blurbs__container--beach-1">
                    <h1 class="container text-center blurbs__container__title">
                        <span class="highlight">Connect</span> with people who live to experience.
                    </h1>
                </div>
            </div>
            <div class="overflow-hidden blurb-2">
                <div class="container-fluid blurbs__container blurbs__container--beach-2">
                    <h1 class="container text-center blurbs__container__title">
                        Be your own boss. Start taking photos <span class="highlight">today</span>.
                    </h1>
                </div>
            </div>
            <div class="overflow-hidden blurb-3">
                <div class="container-fluid blurbs__container blurbs__container--beach-3">
                    <h1 class="container text-center blurbs__container__title">
                        <span class="highlight">Capture</span> those special moments.
                    </h1>
                </div>
            </div>
        </section>
        <section id="join-the-crew" class="join-the-crew container">
            <div class="row">
                <div class="col-sm-6 text-center">
                    <ul class="client-logos">
                        <li>
                            <img class="img-responsive" src="{% static "svg/breather.svg" %}" />
                        </li>
                        <li>
                            <img class="img-responsive" src="{% static "svg/sotheby.svg" %}" />
                        </li>
                        <li>
                            <img class="img-responsive" src="{% static "svg/redfin.svg" %}" />
                        </li>
                        <li>
                            <img class="img-responsive" src="{% static "svg/poshmark.svg" %}" />
                        </li>
                        <li>
                            <img class="img-responsive" src="{% static "svg/cbre.svg" %}" />
                        </li>
                        <li>
                            <img class="img-responsive" src="{% static "svg/rent_like_a_champion.svg" %}" />
                        </li>
                        <li>
                            <img class="img-responsive" src="{% static "svg/postmates.svg" %}" />
                        </li>
                    </ul>
                </div>
                <div class="col-sm-6">
                    <h2 class="regular-font">We’d love to work with you.</h2>
                    <h4 class="">{{ site_display_name }} is a bulk product photography platform that introduces a unique
                        blend of polish and rapidity for for on-demand, marketplace and e-commerce platforms.</h4>
                    <h4 class="text-muted">Make sure your brand is captured in the best way possible. What are you
                        waiting for?</h4>
                    <div>
                        <a href="{% url 'profiles:create' %}">
                            <kendo-button type="submit" ng-cloak class="k-primary">Join now</kendo-button>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $("#id_region").kendoDropDownList();
            $("#id_service_type").kendoDropDownList();
            $("#id_time_period").kendoDropDownList();
            var minDate = moment().add(1, 'day').toDate();
            var datePicker = $("#id_date").kendoDatePicker({
                min: minDate,
                value: minDate
            }).data("kendoDatePicker");
        });
    </script>
{% endblock %}